### PR TITLE
Fix bugs found during alpha test

### LINKED ISSUE #179: [Ben] `add job` allows empty description
- not sure if this is intended
- but it d/ is mandatory, does not make sense to have an empty description right
image

### LINKED ISSUE #180: [Ben] `add job` Example currently does not work due to company integration
- We can either create a sample company Starbuck or change the company in the exmaple

image

### LINKED ISSUE #181: [Ben] `add job` fail silently when a large number is provide as salary
-  I think we can state restriction of the size of salary number in usage message
- handle this gracefully by handling the exception and provide a meaningful feedback to the user

image

image

### LINKED ISSUE #182: [Ben] `add job` invalid feedback message not specific when a negative salary if provided
image

### LINKED ISSUE #183: [Ben] `add job` usage message not specific
- Unsure what is the time period of the salary, is it per month? Maybe we can just specify one and stick to it for now (add allowing different time period as future features)
- What does square bracket mean? Can I specify multiple entries for a specific prefix? See below on how `add contact` address this

image

image

### LINKED ISSUE #185: [Ben] `delete job` gave invalid format error when large index is provided
- Perhaps not the most fitting error message, since I did provide a positive integer

image

### LINKED ISSUE #186: [Ben] `delete job` does not update contact list's match
image

### LINKED ISSUE #194: [General] Remove JobRequirement
I noticed that we are no longer using Job's JobRequirement in our code. We can probably just remove it.

### PR DESCRIPTION
**Pull request by Quasant**
### Provided screenshots within the issues for issue 179, 181, 182, 183, 185

- [x] Closes #179
  - `VALIDATION_REGEX` check implemented within `JobDescription` and `ParserUtil`
- [x] Closes #180 
  - Added an actual Starbucks location to the `sampleDataUtil`
- [x] Closes #181
  - ~~Now I store salary as a string (similar to `Phone`). No artificial limits imposed on user~~
  - Uses isValidSalary to check for NumberFormatException instead
- [x] Closes #182 
  - Changed `MESSAGE_CONTRAINT` and `VALIDATION_REGEX`
- [x] Partially closes #183
  - Monthly Salary UI change
  - ~~The square brackets I left as is, since it was specified in user-guide what [ ] and ... means. Do let me know if you want to enforce the (optional)~~
  - Added (optional), with a somewhat modified command usage formatting
- [x] Closes #185 
  - Actually this issue stemmed from the `deleteCommandParser` so all 3 delete commands were affected by this
  - Since I have no choice but to utilise `parseInt`, I opted for a description change of the delete command 
  - Let me know if you want me to do description change for salary as well and impose the limit or keep my current implementation as string.
- [x] Closes #186 
  - Was fixed in PR #160
- [x] Closes #194

### Undecided, waiting on thoughts 
- #184 
  - This also applies for `Skills`
  - I'm undecided as I can implement the parseException, but that would result in a poorer UX (since instead of auto-merging, the user would have to remove the duplicated tag/skill)
  - Another method that I thought of was to convert the internal representation of tags/skills which is a HashSet into just a List<String>. 
    - I will then need to do 2 checks for duplicate arguments - one within the card UI element and another to modify the add job `SUCCESS_MESSAGE`.

### CODE REVIEW

File: src/main/java/seedu/address/model/job/Job.java [hunk 1]
```diff
@@ -21,9 +21,7 @@ public class Job {
     private final Set<Tag> requirements = new HashSet<>();
 
     /**
-     * TODO: Implement data validation
-     * TODO: What is meant by this ah ^^?
-     * Every field has no validation for now.
+     * Every field must be present and not null.
```
Comment (Quasant) [inline src/main/java/seedu/address/model/job/Job.java:24]: Actually this change was done in a different branch, no idea why it popped up here.

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java [hunk 2]
```diff
@@ -81,7 +82,9 @@ public AddressBook toModelType() throws IllegalValueException {
 
         for (JsonAdaptedJob jsonAdaptedJob : jobs) {
             Job job = jsonAdaptedJob.toModelType();
-            // TODO: Duplicate job invalidation
+            if (addressBook.hasJob(job)) {
+                throw new IllegalValueException(MESSAGE_DUPLICATE_JOB);
+            }
```
Comment (Quasant) [inline src/main/java/seedu/address/storage/JsonSerializableAddressBook.java:87]: Was supposed to be done in another branch, but since its here might as well.

File: src/main/java/seedu/address/model/job/JobDescription.java [hunk 3]
```diff
@@ -1,20 +1,42 @@
...
 public class JobDescription {
+
+    public static final String MESSAGE_CONSTRAINTS =
+            "Job description should not be blank";
+
+    /**
+     * The first character of the address must not be a whitespace,
+     * otherwise " " (a blank string) becomes a valid input.
+     */
+    public static final String VALIDATION_REGEX = "^\\S.*";
```
Comment (KengHian) [inline src/main/java/seedu/address/model/job/JobDescription.java:18]: I am not very good with regex, just to confirm, does this regex allow " " as input description?

File: src/main/java/seedu/address/logic/Messages.java [hunk 4]
```diff
@@ -64,13 +64,11 @@ public static String format(Person person) {
...
-                .append("; Company: ")
+                .append(" at ")
                 .append(job.getCompany())
-                .append("; Salary: ")
+                .append("\n")
                 .append(job.getSalary())
-                .append("; Requirements: ")
-                .append(job.getRequirements())
-                .append("; Description: ")
+                .append("\nDescription: ")
```
Comment (KengHian) [inline src/main/java/seedu/address/logic/Messages.java:71]: While we are no longer using job requirement class, we use tag as its stead, is it something you would want to display here as well?

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 5]
```diff
@@ -20,7 +20,7 @@ public abstract class DeleteCommand<T> extends Command {
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Deletes the entity identified by subcommand 'contact', 'company' or 'job' and "
             + "the index number used in the displayed person list.\n"
-            + "Parameters: [contact/job/company] INDEX (must be a positive integer)\n"
+            + "Parameters: [contact/job/company] INDEX (must be a positive integer between 1 and 2147483647)\n"
```
Comment (KengHian) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:23]: Understood, keep this for now, I will do the necessary changes in a later PR regarding command validation.

File: src/main/java/seedu/address/model/job/JobSalary.java [hunk 6]
```diff
@@ -7,16 +7,16 @@
...
     /*
-     * The first character of the address must not be a whitespace,
-     * otherwise " " (a blank string) becomes a valid input.
+     * The first character of the address must be a digit ranging from 1 to 9. Subsequently, any digit can be inputted.
      */
-    public static final String VALIDATION_REGEX = "[\\p{Digit}][\\p{Digit}]*";
+    public static final String VALIDATION_REGEX = "[1-9][\\p{Digit}]*";
 
-    public final int value;
+    public final String value;
```
Comment (KengHian) [inline src/main/java/seedu/address/model/job/JobSalary.java:19]: I do think storing salary as numbers is preferred as one of our potential feature (screen job with salary) need to compare salary, thus we would need to convert this to number eventually. 

And honestly, 2 billions is a pretty reasonable cap for monthly salary RIGHT?

But this works for now, we can keep it as it is.

File: src/test/java/seedu/address/logic/commands/AddJobCommandTest
Comment (KengHian) [inline src/test/java/seedu/address/logic/commands/AddJobCommandTest:1]: Interesting

File: src/main/java/seedu/address/model/job/JobSalary.java [hunk 7]
```diff
@@ -48,11 +48,11 @@ public boolean equals(Object other) {
...
 
         JobSalary otherSalary = (JobSalary) other;
-        return value == otherSalary.value;
+        return value.equals(otherSalary.value);
     }
 
     @Override
     public String toString() {
-        return "$" + value;
+        return "Monthly Salary: $" + value;
```
Comment (KengHian) [inline src/main/java/seedu/address/model/job/JobSalary.java:56]: If JobSalary is supposed to store monthly salary, perhaps you should reflect that in the class JavaDoc and the usage message as well.

**Review by KengHian — APPROVED** [review]
Overall LGTM, some nitpicks here and there.

**Comment by KengHian** [comment]
- https://github.com/AY2425S1-CS2103-F13-4/tp/issues/184

Regarding this, I don't think we need to perform any functional changes. 

My suggestion was to merely detect the duplication, (perhaps check if `input.size == set.size`), and just add a feedback to the success message that some requirements have been merged.

File: src/main/java/seedu/address/logic/commands/AddJobCommand.java [hunk 8]
```diff
@@ -25,16 +25,15 @@ public class AddJobCommand extends AddCommand<Job> {
             + PREFIX_COMPANY + "COMPANY "
             + PREFIX_SALARY + "SALARY "
             + PREFIX_DESCRIPTION + "DESCRIPTION "
-            + "[" + PREFIX_REQUIREMENTS + "REQUIREMENTS]\n"
+            + "[" + PREFIX_REQUIREMENTS + "REQUIREMENTS]...\n"
```
[the remark this answers is not in the document]
Comment (Quasant) [reply src/main/java/seedu/address/logic/commands/AddJobCommand.java:28]: Actually yes, which is why I also changed the add job success message. 

This is the default UI view for the add job, and you see that `REQUIREMENTS` is too fat. 
image

File: src/main/java/seedu/address/model/job/JobDescription.java (hunk 3 above)
Comment (Quasant) [reply src/main/java/seedu/address/model/job/JobDescription.java:18]: Hahahah I'm also not very good at regex, I just chatgpt and kept re-prompting/trying until one that works appeared. 

Whitespaces as input shown below. 

image

File: src/main/java/seedu/address/logic/commands/AddJobCommand.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (Quasant) [reply src/main/java/seedu/address/logic/commands/AddJobCommand.java:28]: I'm not sure if this is better, but with this I feel a little bit safer adding the optional.

image

File: src/main/java/seedu/address/model/job/JobDescription.java (hunk 3 above)
Comment (Quasant) [reply src/main/java/seedu/address/model/job/JobDescription.java:18]: I have changed it to not use regex. Simpler to understand anyways. The contains '/' check is because I can do something like d/r/reqs and then description becomes "r/reqs".

image

File: src/main/java/seedu/address/model/job/JobSalary.java (hunk 7 above)
Comment (Quasant) [reply src/main/java/seedu/address/model/job/JobSalary.java:56]: Changed!

File: src/test/java/seedu/address/logic/commands/AddJobCommandTest
Comment (Quasant) [reply src/test/java/seedu/address/logic/commands/AddJobCommandTest:1]: Indeed, truly a work of art.

File: src/main/java/seedu/address/model/job/JobSalary.java (hunk 6 above)
Comment (Quasant) [reply src/main/java/seedu/address/model/job/JobSalary.java:19]: I reverted back to storing as an integer, but with the validation check to see if the input is a valid integer (by directly doing the parseInt test and if there is an exception return False).

image

File: src/main/java/seedu/address/logic/Messages.java (hunk 4 above)
Comment (Quasant) [reply src/main/java/seedu/address/logic/Messages.java]: I reverted this back with modification. I changed this originally to modify the Add Job Success message, but I realised it broke other commands that utilised this (i.e. match command) so I simply shifted the changed message to addJobCommand.

File: src/main/java/seedu/address/logic/commands/AddJobCommand.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (KengHian) [reply src/main/java/seedu/address/logic/commands/AddJobCommand.java]: Yeah the latter seems better to me. Looking at the first one, we couldn't even see "Optional" if we add it, so I think it is fine to add for both cases.

File: src/main/java/seedu/address/model/job/JobDescription.java (hunk 3 above)
Comment (KengHian) [reply src/main/java/seedu/address/model/job/JobDescription.java]: The new test does not stop " " from being valid, which is not the expected behavior stated in the JavaDoc.

File: src/main/java/seedu/address/logic/Messages.java (hunk 4 above)
Comment (KengHian) [reply src/main/java/seedu/address/logic/Messages.java]: Sure, so we are still printing our the tags (requirement) in formatting?

File: src/main/java/seedu/address/model/job/JobSalary.java (hunk 7 above)
Comment (KengHian) [reply src/main/java/seedu/address/model/job/JobSalary.java]: I was thinking of adding a note like "(monthly)" beside salary, didn't think you would change everything lol. 

Originally I was thinking of keeping salary general and some of the future features you could specify the time period of the salary.

But this works too, LGTM.

**Review by AlekKwek18 — APPROVED** [review]
LGTM
