### PR TITLE
Branch catch exceptions when loading addressbook

### LINKED ISSUE #189: [JunBoon] `jobCompany Integration` app fail to start when JSON is modified such that job has a non-existing company
- Perhaps a more graceful way is the assume that JSON file is corrupted and start with a fresh JSON file?

image

### LINKED ISSUE #195: [General/JunBoon] Messing with JSON in general results in the UI not loading up the lists
While working on fixing issue #179, I encountered a bug when I implemented validation, in that the sampleData used to load up the app is of an invalid form. I had a thought and realized that (most likely) for all fields, playing around with the JSON would result in an error. 

In JunBoon's case, if I add a unicode character it is an invalid `Name`. 

image

### PR DESCRIPTION
**Pull request by Green-Tea-123**
closes #189 
closes #195 
Added exception handling for CompanyNotFoundException for both loading from json and loading with a sample address book.

### CODE REVIEW

**Review by wassilililily — APPROVED** [review]
LGTM

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java [hunk 1]
```diff
@@ -81,8 +83,10 @@ public AddressBook toModelType() throws IllegalValueException {
 
         for (JsonAdaptedJob jsonAdaptedJob : jobs) {
             Job job = jsonAdaptedJob.toModelType();
-            // TODO: Duplicate job invalidation
-            addressBook.addJob(job);
+            if (addressBook.hasJob(job)) {
+                throw new IllegalValueException(MESSAGE_DUPLICATE_JOB);
+            }
+            addressBook.addJob(job); // this can throw CompanyNotFoundException
```
Comment (Quasant) [inline src/main/java/seedu/address/storage/JsonSerializableAddressBook.java:89]: I touched these exact lines in my PR XD

File: src/main/java/seedu/address/MainApp.java [hunk 2]
```diff
@@ -83,11 +84,17 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
                 logger.info("Creating a new data file " + storage.getAddressBookFilePath()
                         + " populated with a sample AddressBook.");
             }
-            initialData = addressBookOptional.orElseGet(SampleDataUtil::getSampleAddressBook);
+            // line below can throw SampleDataLoadingException
+            ReadOnlyAddressBook sampleAddressBook = SampleDataUtil.getSampleAddressBook();
+            initialData = addressBookOptional.orElse(sampleAddressBook);
```
Comment (Quasant) [inline src/main/java/seedu/address/MainApp.java:89]: Just to confirm this is just a refactoring of getting the AddressBook based off the SampleDataUtil right?

File: src/main/java/seedu/address/MainApp.java [hunk 3]
```diff
@@ -83,11 +84,17 @@ private Model initModelManager(Storage storage, ReadOnlyUserPrefs userPrefs) {
...
         } catch (DataLoadingException e) {
             logger.warning("Data file at " + storage.getAddressBookFilePath() + " could not be loaded."
                     + " Will be starting with an empty AddressBook.");
             initialData = new AddressBook();
+        } catch (SampleDataLoadingException e) {
```
Comment (Quasant) [inline src/main/java/seedu/address/MainApp.java:94]: I realised my issue was poorly phrased and might have misled you hahaahha. The sampleData shouldn't have an exception, since we ourselves chose the data within there (unless the user go and modify it, but that one do we really need to defend against)

Comment (Quasant) [reply src/main/java/seedu/address/MainApp.java:94]: Rather, what I meant was that on a non fresh start (i.e. the addressbook JSON already exists), I can modify the data file to give a VALIDATION_REGEX error.

File: src/main/java/seedu/address/storage/JsonAddressBookStorage.java [hunk 4]
```diff
@@ -56,6 +57,9 @@ public Optional<ReadOnlyAddressBook> readAddressBook(Path filePath) throws DataL
         } catch (IllegalValueException ive) {
             logger.info("Illegal values found in " + filePath + ": " + ive.getMessage());
             throw new DataLoadingException(ive);
+        } catch (CompanyNotFoundException cnfe) {
+            logger.info("Job associated with non-existent company in " + filePath + ": " + cnfe.getMessage());
+            throw new DataLoadingException(cnfe);
```
Comment (Quasant) [inline src/main/java/seedu/address/storage/JsonAddressBookStorage.java:62]: Nice. I will probably fix the non-existing match issue that KH raised for me in the same way as this.

**Review by Quasant — APPROVED** [review]
LGTM! Thousand apologies for the sampleData extra work.

File: src/main/java/seedu/address/MainApp.java (hunk 2 above)
Comment (Green-Tea-123) [reply src/main/java/seedu/address/MainApp.java:89]: This is because java will throw an error if I set the function that throws the exception in the orElseGet method.

File: src/main/java/seedu/address/MainApp.java (hunk 3 above)
Comment (Green-Tea-123) [reply src/main/java/seedu/address/MainApp.java:94]: Yeah I understand as well. Just wanted to add the checks in both cases I guess.

Comment (Green-Tea-123) [reply src/main/java/seedu/address/MainApp.java:94]: The addition of the new exception was actually to adding a more specific logger warning to say that something was wrong with the loading of the sample data.

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java (hunk 1 above)
Comment (Green-Tea-123) [reply src/main/java/seedu/address/storage/JsonSerializableAddressBook.java:89]: I just saw it was TODO and it was quite simple so I implemented it lol
